name: 更新简历到服务器

on:
  push:
    # push代码的时候哪个分支会受到影响、这里是main主分克
    branches:
      - main
      
# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库action/checkout获取代码
        uses: actions/checkout@main

      # 部署到腾讯云服务器
      - name: 发布到腾讯云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTET_XHOST }} # 服务器域名
          username: 'root' # 腾讯云默认用户名为root
          key: ${{ secrets.PRIVATE_KEY }} # 本地.ssh文件下的私钥id_rsa，存在secrets中
          source: './dist' # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          target: '/data/www/resume' # 目标目录
