name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - main # 根据你的分支设置修改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 使用action库action/checkout获取代码
      - name: 迁出代码
        uses: actions/checkout@v4


      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: 安装项目依赖
        run: npm install

      - name: 构建项目
        run: npm run build

      - name: 发布到腾讯云
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          # 将私钥写入文件
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
  
          # 删除服务器旧文件
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "rm -rf /home/docker_project/site/resume.heinfy.top/*"
  
          # 上传新文件
          scp -i private_key -o StrictHostKeyChecking=no -r ./dist/* $SERVER_USER@$SERVER_HOST:/home/docker_project/site/resume.heinfy.top/
  
          # 删除本地私钥
          rm private_key
